src/main/java/com/cgi/osd/transactiondemo/presentation/gui/BookingManagerController.java
package com.cgi.osd.transactiondemo.presentation.gui;

import java.io.Serializable;
import java.security.Principal;
import java.util.List;
import java.util.logging.Logger;

import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.cgi.osd.transactiondemo.logic.BookingManagerService;
import com.cgi.osd.transactiondemo.logic.domainobject.CustomerDO;

@SessionScoped
@Named
public class BookingManagerController implements Serializable {

    private static final long serialVersionUID = 1L;

    @Inject
    Principal principal;

    @Inject
    private Logger logger;

    @Inject
    BookingManagerData bookingManagerData;

    @Inject
    BookingManagerService bookingManagerService;

    private CustomerDO selected = new CustomerDO(null, null, null, null, null, null, null);

    public List<CustomerDO> getAllBookings() {
	return this.bookingManagerData.getAllBookings();
    }

    public CustomerDO getSelected() {
	return selected;
    }

    public void setSelected(CustomerDO selected) {
	this.selected = selected;
    }

    public String getPrincipal() {
	return principal.getName();
    }

    public List<CustomerDO> getCustomerBooking() {
	return this.bookingManagerData.getCustomerBooking(getPrincipal());
    }

    //
    public void deleteBooking() {
	bookingManagerService.removeBooking(selected);
    }
}

src/main/webapp/user/showBookings.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	template="/WEB-INF/templates/list.xhtml">

	<ui:define name="content">
		<h:form id="form">
			<p:dataTable id="bookings" var="booking"
				value="#{bookingManagerController.customerBooking}"
				rowKey="#{booking.firstName}"
				selection="#{bookingManagerController.selected}" selectionMode="single"
				reflow="true">
				<f:facet name="header">
            All Bookings
        </f:facet>
				<p:column style="width:16px">
					<p:rowToggler />
				</p:column>
				<p:column headerText="firstname">
					<h:outputText value="#{booking.firstName}" />
				</p:column>
				<p:column headerText="lastname">
					<h:outputText value="#{booking.lastName}" />
				</p:column>
				<p:column headerText="email">
					<h:outputText value="#{booking.email}" />
				</p:column>
				<p:column headerText="phone">
					<h:outputText value="#{booking.phone}" />
				</p:column>
				<p:column headerText="date">
					<h:outputText value="#{booking.date}" />
				</p:column>
				<p:column style="width:32px;text-align: center">
					<p:commandButton icon="ui-icon-trash"
						action="#{bookingManagerController.deleteBooking()}" update="bookings" >
					<f:setPropertyActionListener target="#{bookingManagerController.selected}" value="#{booking}"  />
						<p:confirm header="Confirmation" message="Are you sure?" icon="ui-icon-alert" />
					</p:commandButton>
				</p:column>
				<p:rowExpansion>
					<p:panelGrid columns="2" columnClasses="label,value"
						style="width:350px" layout="grid">
						<h:outputText value="Seats:" />
						<ui:repeat value="#{booking.bookedSeats}" var="seat"
							varStatus="status">
							<h:outputText value="#{seat.seatNumber}, " />
						</ui:repeat>
						<h:outputText value="Payment" />
						<h:outputText value="#{booking.payments.get(0).amount}:-" />
					</p:panelGrid>
				</p:rowExpansion>
			</p:dataTable>
			<br />
			<p:commandButton value="Logout" icon="ui-icon-extlink"
				action="#{logoutBean.logout}" />
			<ui:include src="/confirmation.xhtml" />
		</h:form>
	</ui:define>
</ui:composition>