src/main/java/com/cgi/osd/transactiondemo/integration/EmailUtilBean.java
package com.cgi.osd.transactiondemo.integration;

import java.util.List;
import java.util.logging.Logger;

import javax.annotation.Resource;
import javax.ejb.Asynchronous;
import javax.ejb.Stateless;
import javax.inject.Inject;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

import com.cgi.osd.transactiondemo.logic.domainobject.CustomerDO;
import com.cgi.osd.transactiondemo.logic.domainobject.SeatDO;

@Stateless
public class EmailUtilBean implements EmailUtil {

    public EmailUtilBean() {

    }

    @Inject
    private Logger logger;

    @Resource(mappedName = "java:jboss/mail/Gmail")
    Session gmailSession;

    @Asynchronous
    @Override
    public void sendEmail(CustomerDO customer, List<SeatDO> bookedSeats, String password) {

	final int price = 200;
	final String toEmail = customer.getEmail();
	final String from = "NoReply-CGI_LIA";
	final String subject = "Bokningsbekräftelse";
	final String content = "Tack för din bokning!" + "\n" + "\n" + customer.getFirstName() + " "
		+ customer.getLastName() + "\n" + customer.getEmail() + "\n" + customer.getPhone() + "\n"
		+ "Bokade platser: " + bookedSeats.size() + "\n" + "Pris: " + bookedSeats.size() * price + "Kr" + "\n"
		+ "\n" + "Inloggningsuppgifter: " + "\n" + "Användarnamn: " + customer.getEmail() + "\n" + "Lösenord: "
		+ password + "\n" + "\n" + "En faktura skickas ut via email inom 30 dagar.";

	logger.info("Sending Email from " + from + " to " + toEmail + " : " + subject);
	try {
	    Message message = new MimeMessage(gmailSession);
	    message.setFrom(new InternetAddress(from));
	    message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(toEmail));
	    message.setSubject(subject);
	    message.setText(content);

	    Transport.send(message);
	    logger.info("Email was sent");

	} catch (MessagingException e) {
	    logger.severe("Error while sending email : " + e.getMessage());
	}
    }
}

src/main/java/com/cgi/osd/transactiondemo/integration/LogoutBean.java
package com.cgi.osd.transactiondemo.integration;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

@Named(value = "logoutBean")
@RequestScoped
public class LogoutBean {

    private static Logger log = Logger.getLogger(LogoutBean.class.getName());

    public String logout() {
	String destination = "/index?faces-redirect=true";
	FacesContext context = FacesContext.getCurrentInstance();
	HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();

	try {
	    HttpSession session = request.getSession();
	    session.invalidate();
	    request.logout();
	} catch (ServletException e) {
	    log.log(Level.SEVERE, "Failed to logout user!", e);
	    destination = "/loginerror?faces-redirect=true";
	}
	return destination;
    }

    public void endBooking() {
	FacesContext context = FacesContext.getCurrentInstance();
	HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
	try {
	    HttpSession session = request.getSession();
	    session.invalidate();
	    request.logout();
	} catch (ServletException e) {
	}
    }
}

src/main/java/com/cgi/osd/transactiondemo/integration/PersistenceManagerBean.java
package com.cgi.osd.transactiondemo.integration;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

import javax.ejb.Stateless;
import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;
import javax.ejb.TransactionManagement;
import javax.ejb.TransactionManagementType;
import javax.inject.Inject;
import javax.interceptor.Interceptors;
import javax.persistence.EntityManager;
import javax.persistence.LockModeType;
import javax.persistence.TypedQuery;

import com.cgi.osd.student.paymentserver.soap.PaymentFault_Exception;
import com.cgi.osd.student.paymentserver.soap.PaymentRequestDTO;
import com.cgi.osd.student.paymentserver.soap.PaymentResponseDTO;
import com.cgi.osd.student.paymentserver.soap.PaymentService;
import com.cgi.osd.transactiondemo.logic.domainobject.CustomerDO;
import com.cgi.osd.transactiondemo.logic.domainobject.SeatDO;
import com.cgi.osd.transactiondemo.logic.domainobject.UserDO;
import com.cgi.osd.transactiondemo.logic.exception.PersistenceOperationException;

/**
 * This class is responsible for implementing methods for persistence handling.
 * All methods are thread safe.
 *
 */
@Stateless
@TransactionManagement(TransactionManagementType.CONTAINER)
@TransactionAttribute(TransactionAttributeType.NEVER)
@Interceptors(ExceptionInterceptor.class)
public class PersistenceManagerBean implements PersistenceManager {

    @Inject
    private EntityManager em;

    @Inject
    private PersistenceObjectFactory objectFactory;

    @Inject
    RestService restService;

    @Inject
    Logger logger;

    @Override
    @TransactionAttribute(TransactionAttributeType.REQUIRES_NEW)
    public List<SeatDO> getAllSeats() {
	final List<Seat> dbResult = fetchAllSeats();
	final List<SeatDO> result = this.objectFactory.createSeatDOList(dbResult);
	return result;
    }

    List<Seat> fetchAllSeats() {
	final TypedQuery<Seat> query = this.em.createNamedQuery("Seat.findAll", Seat.class);
	query.setLockMode(LockModeType.OPTIMISTIC);
	final List<Seat> dbResult = query.getResultList();
	return dbResult;
    }

    public List<Seat> fetchAllSelectedSeats(List<Integer> selectedSeats) {
	final TypedQuery<Seat> querySeats = this.em.createNamedQuery("Seat.findSelectedSeats", Seat.class);
	querySeats.setParameter("seatNumber", selectedSeats);

	final List<Seat> dbResult = querySeats.getResultList();
	return dbResult;
    }

    @Override
    @TransactionAttribute(TransactionAttributeType.REQUIRES_NEW)
    public List<SeatDO> getAllSelectedSeats(List<Integer> selectedSeats) {
	final List<Seat> dbResult = fetchAllSelectedSeats(selectedSeats);
	final List<SeatDO> result = this.objectFactory.createSeatDOList(dbResult);
	return result;
    }

    @Override
    @TransactionAttribute(TransactionAttributeType.REQUIRES_NEW)
    public int insertNewCustomer(CustomerDO customerDO, UserDO userDO) throws PersistenceOperationException {
	final int customerId;
	final Customer customer = this.objectFactory.createCustomer(customerDO);
	final User user = objectFactory.createNewUser(userDO);
	user.setRole("USER");

	em.persist(customer);
	em.persist(user);
	em.flush();
	customerId = customer.getPKey();
	return customerId;
    }

    @Override
    @TransactionAttribute(TransactionAttributeType.REQUIRES_NEW)
    public void deleteBooking(CustomerDO customerDO) {
	final TypedQuery<Customer> queryCustomer = this.em.createNamedQuery("Customer.findByEmail", Customer.class);
	queryCustomer.setParameter("email", customerDO.getEmail());

	Customer dbResult = queryCustomer.getSingleResult();

	List<Integer> customerSeats = new ArrayList<>();
	for (Seat seat : dbResult.getSeats()) {
	    customerSeats.add(seat.getSeatNumber());
	}

	final TypedQuery<Seat> querySeat = this.em.createNamedQuery("Seat.findSelectedSeats", Seat.class);
	querySeat.setParameter("seatNumber", customerSeats);

	List<Seat> seats = querySeat.getResultList();
	for (Seat seat : seats) {
	    seat.setSeatLock(0);
	    seat.setCustomerBean(null);
	    em.merge(seat);
	}
	em.remove(dbResult);
    }

    @Override
    @TransactionAttribute(TransactionAttributeType.REQUIRES_NEW)
    public void createBooking(int customerId, List<Integer> byCustomerSelectedSeats,
	    PaymentRequestDTO paymentRequestDTO) {
	PaymentResponseDTO paymentResponseDTO = performPayment(paymentRequestDTO);
	final int locked = 1;
	final TypedQuery<Customer> queryCustomer = this.em.createNamedQuery("Customer.findById", Customer.class);
	queryCustomer.setParameter("pKey", customerId);

	final List<Seat> seatList = fetchAllSelectedSeats(byCustomerSelectedSeats);
	for (Seat seat : seatList) {
	    seat.setSeatLock(locked);
	}
	final Customer customer = queryCustomer.getSingleResult();
	final Payment payment = objectFactory.createPayment(paymentResponseDTO);
	customer.setSeats(seatList);
	customer.addPayment(payment);

	for (Seat seat : seatList) {
	    seat.setCustomerBean(customer);
	}
	payment.setCustomerBean(customer);
	em.persist(payment);
	em.merge(customer);
	new LogoutBean().endBooking();
    }

    @Override
    @TransactionAttribute(TransactionAttributeType.REQUIRES_NEW)
    public List<CustomerDO> getAllbookings() {
	final List<Customer> dbresult = fetchAllBookings();
	final List<CustomerDO> result = objectFactory.createCustomerDOList(dbresult);
	return result;

    }

    public List<Customer> fetchAllBookings() {
	final TypedQuery<Customer> queryCustomer = this.em.createNamedQuery("Customer.findAll", Customer.class);
	final List<Customer> dbResult = queryCustomer.getResultList();
	return dbResult;

    }

    public List<Customer> fetchCustomerByEmail(String userName) {
	final TypedQuery<Customer> queryCustomer = this.em.createNamedQuery("Customer.findByEmail", Customer.class);
	queryCustomer.setParameter("email", userName);

	final List<Customer> dbResult = queryCustomer.getResultList();
	return dbResult;
    }

    @Override
    @TransactionAttribute(TransactionAttributeType.REQUIRES_NEW)
    public List<CustomerDO> getCustomerByEmail(String userName) {
	final List<Customer> dbResult = fetchCustomerByEmail(userName);
	final List<CustomerDO> result = this.objectFactory.createCustomerDOList(dbResult);
	return result;
    }

    private PaymentResponseDTO performPayment(PaymentRequestDTO paymentRequestDTO) {
	if ("REST".equals(System.getProperty("paymentService"))) {
	    return restPayment(paymentRequestDTO);
	} else {
	    try {
		return soapPayment(paymentRequestDTO);
	    } catch (PaymentFault_Exception e) {
		e.printStackTrace();
	    }
	}
	logger.severe("Add missing system property for payment service");
	return null;
    }

    private PaymentResponseDTO soapPayment(PaymentRequestDTO paymentRequestDTO) throws PaymentFault_Exception {
	PaymentResponseDTO paymentResponseDTO = new PaymentService().getPaymentServiceSOAP()
		.performPurchase(paymentRequestDTO);
	return paymentResponseDTO;
    }

    private PaymentResponseDTO restPayment(PaymentRequestDTO paymentRequestDTO) {
	PaymentResponseDTO responseDTO = restService.postPayment(paymentRequestDTO);
	return responseDTO;
    }

}

src/main/java/com/cgi/osd/transactiondemo/integration/RestServiceBean.java
package com.cgi.osd.transactiondemo.integration;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.ws.rs.Consumes;
import javax.ws.rs.POST;
import javax.ws.rs.Produces;
import javax.ws.rs.client.Entity;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.MediaType;

import com.cgi.osd.student.paymentserver.soap.PaymentRequestDTO;
import com.cgi.osd.student.paymentserver.soap.PaymentResponseDTO;

@Named
@RequestScoped
@Consumes("application/json")
@Produces("application/json")
public class RestServiceBean implements RestService {

    @Inject
    RestClientBuilder restClientBuilder;

    @POST
    @Override
    public PaymentResponseDTO postPayment(PaymentRequestDTO request) {
	WebTarget myResource = restClientBuilder.getClient()
		.target("http://studentpaymentserver-cgiostersund.rhcloud.com/paymentserver/rest/paymentservices/pay");

	PaymentResponseDTO response = myResource.request(MediaType.APPLICATION_JSON).post(Entity.json(request),
		PaymentResponseDTO.class);
	return response;
    }
}

src/main/java/com/cgi/osd/transactiondemo/logic/BookingManagerServiceBean.java
package com.cgi.osd.transactiondemo.logic;

import java.util.List;
import java.util.logging.Logger;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;

import com.cgi.osd.transactiondemo.integration.PersistenceManager;
import com.cgi.osd.transactiondemo.logic.domainobject.CustomerDO;

@ApplicationScoped
public class BookingManagerServiceBean implements BookingManagerService {

    @Inject
    Logger logger;

    @Inject
    private PersistenceManager persistenceManager;

    @Override
    public List<CustomerDO> getAuthenticatedCustomer(String userName) {
	List<CustomerDO> customerDO = persistenceManager.getCustomerByEmail(userName);
	return customerDO;
    }

    @Override
    public void removeBooking(CustomerDO customerDO) {
	persistenceManager.deleteBooking(customerDO);
    }

    @Override
    public List<CustomerDO> getAllBookings() {
	final List<CustomerDO> allBookings = persistenceManager.getAllbookings();
	return allBookings;
    }
}

src/main/java/com/cgi/osd/transactiondemo/logic/BookingServiceBean.java
package com.cgi.osd.transactiondemo.logic;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;

import com.cgi.osd.student.paymentserver.soap.PaymentRequestDTO;
import com.cgi.osd.transactiondemo.integration.PersistenceManager;
import com.cgi.osd.transactiondemo.logic.domainobject.CustomerDO;
import com.cgi.osd.transactiondemo.logic.domainobject.SeatDO;
import com.cgi.osd.transactiondemo.logic.domainobject.UserDO;
import com.cgi.osd.transactiondemo.logic.exception.PersistenceOperationException;

/**
 * This class is responsible for implementing the booking services.
 *
 * @author anderssonhr
 *
 */

@ApplicationScoped
public class BookingServiceBean implements BookingService {

    @Inject
    Logger logger;

    @Inject
    private PersistenceManager persistenceManager;

    /*
     * (non-Javadoc)
     *
     * @see com.cgi.osd.transactiondemo.logic.BookingService#getAllSeats()
     */
    @Override
    public List<SeatDO> getAllSeats() throws PersistenceOperationException {
	final List<SeatDO> seats = persistenceManager.getAllSeats();
	return seats;
    }

    @Override
    public void createBooking(CustomerDO customerDO, List<SeatDO> selectedSeats, UserDO userDO,
	    PaymentRequestDTO paymentRequestDTO) throws PersistenceOperationException {
	final int customerId = persistenceManager.insertNewCustomer(customerDO, userDO);
	persistenceManager.createBooking(customerId, convertSeatnumberToInteger(selectedSeats), paymentRequestDTO);

    }

    @Override
    public List<SeatDO> checkSeatVersion(List<SeatDO> selectedSeats) {
	List<SeatDO> selectedSeatsToCompare = persistenceManager
		.getAllSelectedSeats(convertSeatnumberToInteger(selectedSeats));
	return selectedSeatsToCompare;
    }

    public List<Integer> convertSeatnumberToInteger(List<SeatDO> selectedSeats) {
	List<Integer> seatNumbers = new ArrayList<>();
	for (SeatDO seats : selectedSeats) {
	    seatNumbers.add(seats.getSeatNumber());
	}
	return seatNumbers;
    }
}

src/main/java/com/cgi/osd/transactiondemo/presentation/gui/BookingManagerController.java
package com.cgi.osd.transactiondemo.presentation.gui;

import java.io.Serializable;
import java.security.Principal;
import java.util.List;
import java.util.logging.Logger;

import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.cgi.osd.transactiondemo.logic.BookingManagerService;
import com.cgi.osd.transactiondemo.logic.domainobject.CustomerDO;

@SessionScoped
@Named
public class BookingManagerController implements Serializable {

    private static final long serialVersionUID = 1L;

    @Inject
    Principal principal;

    @Inject
    private Logger logger;

    @Inject
    BookingManagerData bookingManagerData;

    @Inject
    BookingManagerService bookingManagerService;

    private CustomerDO selected = new CustomerDO(null, null, null, null, null, null, null);

    public List<CustomerDO> getAllBookings() {
	return this.bookingManagerData.getAllBookings();
    }

    public CustomerDO getSelected() {
	return selected;
    }

    public void setSelected(CustomerDO selected) {
	this.selected = selected;
    }

    public String getPrincipal() {
	return principal.getName();
    }

    public List<CustomerDO> getCustomerBooking() {
	return this.bookingManagerData.getCustomerBooking(getPrincipal());
    }

    //
    public void deleteBooking() {
	bookingManagerService.removeBooking(selected);
    }
}

src/main/webapp/bookingConfirmation.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core">

<h:form>	
      <h1>Thank you for your booking!</h1>
    <p:commandButton value="Booking page" style="left" icon="ui-icon-check" action="/index?faces-redirect=true"/>	
</h:form>
</ui:composition>

src/main/webapp/bookingpage.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/templates/default.xhtml">
	<ui:define name="content">
		<p:tabView dynamic="true" cache = "false">
			<p:tab title="Booking Confirmation">
				<ui:include src="/bookingConfirmation.xhtml" />				
			</p:tab>
		</p:tabView>
	</ui:define>
</ui:composition>

src/main/webapp/bookwizard.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core">
		
	<h:form>              
    <p:growl id="growl" sticky="true" showDetail="true"/>
    <p:wizard flowListener="#{bookingController.onFlowProcess}">
        <p:tab id="seats" title="Seats">
            <p:panel header="Select seats">
                <p:messages />
                <h:panelGrid columns="2" columnClasses="label, value">
                    <p:selectManyButton required="true" styleClass="manyBtn"
				converter="omnifaces.SelectItemsConverter" label="Seat"
				id="selectedButton" value="#{bookingController.selectedSeats}"  >

				<f:selectItems value="#{bookingController.allSeats}" var="seats"
					itemLabel="#{seats.seatNumber}" itemValue="#{seats}" 
					itemDisabled="#{bookingController.disableSeats(seats.seatLock)}"/>					
				</p:selectManyButton>
                </h:panelGrid>
            </p:panel>
        </p:tab>
 
        <p:tab id="personal" title="Personal">
            <p:panel header="Person Details">
                <p:messages />
                <h:panelGrid columns="2" columnClasses="label, value">
                    <h:outputText value="Firstname: *" />
                    <p:inputText id="firstName" value="#{bookingController.customerDO.firstName}" required="true" label="Firsname" >
                    <f:validateLength minimum="2" />
                    </p:inputText>
 
                    <h:outputText value="Lastname: *" />
                    <p:inputText id="lastName" value="#{bookingController.customerDO.lastName}" required="true" label="Lastname">
                    <f:validateLength minimum="2" />
                    </p:inputText>
 
                    <h:outputText value="Email: *" />
                    <p:inputText id="email" value="#{bookingController.customerDO.email}" required="true" label="Email">
                    <f:validateLength minimum="2" />
                    </p:inputText>
                    
                    <h:outputText value="Phone: *" />
                    <p:inputMask id="custPhone"
					value="#{bookingController.customerDO.phone}" required="true"
					label="Phone" mask="999-9999999">
					</p:inputMask>
                </h:panelGrid>
            </p:panel>
        </p:tab>
 
        <p:tab id="payment" title="Payment">
            <p:panel header="Payment Details">
                <p:messages />
                <h:panelGrid columns="2" columnClasses="label, value">
                    <h:outputText value="Cardholder name: *" />
                    <p:inputText id="cardName" value="#{bookingController.paymentRequestDTO.cardHolderName}" required="true" label="Name">
                    <f:validateLength minimum="2" />
                    </p:inputText>
 
                    <h:outputText value="Card nr: *" />
                    <p:inputMask id="cardNr"
					value="#{bookingController.paymentRequestDTO.cardNumber}" required="true"
					label="Card Nr" mask="9999">
					</p:inputMask>
                </h:panelGrid>
            </p:panel>
        </p:tab>
 
        <p:tab id="confirm" title="Confirmation">
            <p:panel header="Confirmation" styleClass="confirmation">
                <h:panelGrid id="confirmation" columns="1" columnClasses="grid" styleClass="datalist-noborder">
                    <h:panelGrid columns="2" columnClasses="label, value">
                        <h:outputText styleClass="outputText" value="Firstname: " />
                        <h:outputText value="#{bookingController.customerDO.firstName}" styleClass="outputLabel"/>
 
                        <h:outputText styleClass="outputText" value="Lastname: " />
                        <h:outputText value="#{bookingController.customerDO.lastName}" styleClass="outputLabel"/>
 
                        <h:outputText styleClass="outputText" value="Email: " />
                        <h:outputText value="#{bookingController.customerDO.email}" styleClass="outputLabel"/>
                        
                        <h:outputText styleClass="outputText" value="Phone: "/>
                        <h:outputText value="#{bookingController.customerDO.phone}" styleClass="outputLabel"/>
                                              
                        <h:outputText styleClass="outputText" value="Seat: " />
                        <p:dataList value="#{bookingController.selectedSeats}" var="seat" styleClass="outputLabel" type="definition">
    						  		#{seat.seatNumber}
   						</p:dataList>

                        <h:outputText styleClass="outputText" value="Cardholder: " />
                        <h:outputText value="#{bookingController.paymentRequestDTO.cardHolderName}" styleClass="outputLabel"/>
 
                        <h:outputText styleClass="outputText" value="Card nr: " />
                        <h:outputText value="#{bookingController.paymentRequestDTO.cardNumber}" styleClass="outputLabel"/>  
                        
                        <h:outputText styleClass="outputText" value="Price: " />
                        <h:outputText value="#{bookingController.selectedSeats.size()*200}:-" styleClass="outputLabel"/>  
                    </h:panelGrid>
                </h:panelGrid>
 					<br/>
                <p:commandButton value="Submit" action="#{bookingController.createBooking()}" update="growl" process="@this">
                </p:commandButton>
            </p:panel>
        </p:tab>
    </p:wizard>
    <h3 > <p:link id="h3viewBookings" outcome="user/showBookings" value="Click here to view your bookings."></p:link></h3>
</h:form>	
</ui:composition>	
	

src/main/webapp/confirmation.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">

    <p:confirmDialog global="true">  
        <p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check"/>  
        <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close"/>       
    </p:confirmDialog>

</ui:composition>

src/main/webapp/failpage.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	template="/WEB-INF/templates/default.xhtml">
	<ui:define name="content">
<h:form>
      <h1>Booking failed, please try again!</h1>	
    <p:commandButton value="Booking page" style="left" icon="ui-icon-check" action="/index?faces-redirect=true"/>	
</h:form>
</ui:define>
</ui:composition>

src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/templates/default.xhtml">
	<ui:define name="content">	
		<ui:include src="/bookwizard.xhtml" />	
	</ui:define>
</ui:composition>

src/main/webapp/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core">
    <h:head>
        <title>Login</title>
        <h:outputStylesheet name="css/LoginStyle.css" />
    </h:head>
   		
        <form method="post" action="j_security_check">
  			<header>Login</header>
  			<label>Email<span>*</span></label>
  			<input type="text" name="j_username" required="true"/>
  			<label>Password <span>*</span></label>
  			<input type="password" name="j_password" required="true"/>
  		<!-- <div class="help">Use numbers, upper and lowercase letters as well</div> -->
  			<button action="submit">Sign in</button>
			</form>
</ui:composition>

src/main/webapp/loginerror.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui" 
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
        <title>Login Error </title>
        <h:outputStylesheet name="css/LoginStyle.css" />
    </h:head>
    <h:body>
        <p:panel header="Login Error">
            Wrong username or password. <br />Please try again: <a href="#{facesContext.externalContext.requestContextPath}/" >Homepage</a>
        </p:panel>
    </h:body>
</html>